### ISSUE TITLE
convenience method of .mock off the mocked object

### ISSUE THREAD

**Issue by bkirkby** [clarkedb/grift#250]
right now in order for me to get info about the mock from the mocked object/method, i have to hit mocked_method.mock.<info>. would be nice to just do mocked_method.<info>

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the MockMethod class to expose information methods directly, eliminating the need to access them through the 'mock' property. This change improves the user experience by allowing direct access to mock information.

You can review changes in this commit: https://github.com/mnmnk43434/clarkedb-grift-250/commit/742fa7fd953af7d5c663bf3e17994388888b7855.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by birdsean** [comment]
Came here to say this ^. Every time I go to mock something I have to think twice when I have to do `mock.mock.count`, which I then turn into `suspender_mock.mock.count` or something like that. Would be easier to read my code and more ergonomic if I would just `mock.count` or `suspender_mock.count`
